### ISSUE TITLE
Named workspaces

### ISSUE THREAD

**Issue by YaLTeR** [YaLTeR/niri#201]
Idea suggested by `m` on Matrix. I think this can solve the "open multiple windows on different workspaces at startup" problem without compromising much of the dynamic workspaces workflows like rearranging, moving between monitors, etc.

Roughly as follows:
- Have a way to declare named workspaces in the config
- They can have an associated output where they will be placed at startup
  - I guess this will only be done once at startup, otherwise they follow the normal workspace-monitor positioning logic. I.e. if the associated output is only connected later, they don't move there automatically.
  - If the associated output is missing at startup, they are placed on the primary output
- You cannot have multiple named workspaces with the same name
- Empty named workspaces don't get cleaned up, otherwise behave exactly the same as normal workspaces. You can move them around, to different monitors, etc. In the code just add a `name: Option<String>` to `Workspace`
- Actions like focus-workspace, move-column-to-workspace can address workspaces by name
- Add a window rule for `open-on-workspace "name"`

One problem is that in an absence of a built-in bar, there's no indication that some workspace is a named workspace. It can get confusing, especially if all windows on one are closed, and it's moved around.

**Comment by jgregoire** [comment]
I could write my own bar workspace plugin if there was an IPC call to get an ordered list of workspaces and the active workspace id.

What I would find quite valuable is an events system that I could subscribe plugins/tools to. So if the workspace changed, I could update my workspace plugin without needing to poll via IPC.

Example events:

- Window spawned, focused, moved, killed.
- Workspace spawned, focused, moved, killed.
- Config updated.

Having access to such signals is one of the greatest features of awesomewm IMO.

**Comment by YaLTeR** [comment]
Yes, that is planned, and thanks for the ideas for events. However, it is not related to this issue at all?

**Comment by TheZoq2** [comment]
This would be a great change. "Persistent workspaces" is something I really miss from other WMs

**Comment by algernon** [comment]
I had a quick look at the code, and... I think I have an idea. Not for the declaring it in the config part (but I hope that should be the easier part), but the rest. A quick read of relevant code (mostly `src/layout/mod.rs`) suggests that if there was a way to prevent workspaces from closing when they become empty, and a way to create them on startup, that'd be enough to implement named namespaces.

So... what if `Workspace` had a `name: Option<String>` member, and if that was `Some`, it would not be deleted. Simple as that. To accomplish this, `Vec<Workspace<W>>` could be abstracted away into something like `Workspaces<W>`, which could have a `maybe_remove()` function or similar implemented, which would do the checking for the name, so it doesn't have to be repeated every time a workspace is  to be removed. This way, existing named workspaces would be exempt from deletion.

Creating them would be restricted to doing so as response to configuration, new  named workspaces would not be creatable at runtime.

Addressing them by name would require a few more helper functions that walk the workspace vector, and look for a name. While this isn't a particularly cheap operation, I'm going with the assumption that looking up workspaces by name will not be such a frequent operation that a more efficient lookup would be worth it - but one can always be added later, if it becomes a problem.

I *think* this could work, but there are a number of corner cases that I want to explore, like how named & dynamic workspaces interact, and what happens if I have a bunch of named ones, a few dynamic ones, and reload the config that adds (or removes) a named one. I suppose removing a named workspace would be as easy as setting its `name` to `None` - this way its windows and whatnot would not need moving, it would just turn into a regular dynamic workspace. The more interesting case is where I'd have: `[ NamedWorkspace1, NamedWorkspace2, DynamicWorkspace1, NamedWorkspace3, DynamicWorkspace2 ]` in the workspaces vector, and dropped `DynamicWorkspace1`.

Also worth exploring is whether it makes sense to be able to address named workspaces by index too, or just by name.

I'll run with this idea tomorrow, and see where it leads. I just wanted to dump it here, maybe someone spots something obviously wrong with it.

**Comment by YaLTeR** [comment]
> a way to prevent workspaces from closing when they become empty, and a way to create them on startup, that'd be enough to implement named namespaces.

Yep.

> So... what if Workspace had a `name: Option<String>` member, and if that was `Some`, it would not be deleted. Simple as that.

Yes, that was what I was thinking.

> Vec<Workspace<W>> could be abstracted away into something like Workspaces<W>, which could have a maybe_remove() function or similar implemented, which would do the checking for the name, so it doesn't have to be repeated every time a workspace is to be removed.

Pretty sure the only place where removing happens is `Monitor::clean_up_workspaces()`, so no need for structural changes.

> Creating them would be restricted to doing so as response to configuration, new named workspaces would not be creatable at runtime.

That makes sense. Also I guess removing a named workspace from config would convert it to an unnamed workspace? (I see you had the same idea below.)

> Addressing them by name would require a few more helper functions that walk the workspace vector, and look for a name. While this isn't a particularly cheap operation, I'm going with the assumption that looking up workspaces by name will not be such a frequent operation that a more efficient lookup would be worth it - but one can always be added later, if it becomes a problem.

I agree. We use quite a lot of linear scans currently, I'm not entirely happy about some of them, but realistically with less than 10 entries it's not gonna pose a problem.

> I *think* this could work, but there are a number of corner cases that I want to explore, like how named & dynamic workspaces interact

Hm, what are the corner cases? I didn't do any in-depth thinking on this but I feel like they just interact as normal with no changes (other than preventing clean-up).

> The more interesting case is where I'd have: `[ NamedWorkspace1, NamedWorkspace2, DynamicWorkspace1, NamedWorkspace3, DynamicWorkspace2 ]` in the workspaces vector, and dropped `DynamicWorkspace1`.

Just `[ NamedWorkspace1, NamedWorkspace2, NamedWorkspace3, DynamicWorkspace2 ]`?

> Also worth exploring is whether it makes sense to be able to address named workspaces by index too, or just by name.

In my mind they behave just like any other workspace, except they also have a name, so yes.

**Comment by algernon** [comment]
> Just `[ NamedWorkspace1, NamedWorkspace2, NamedWorkspace3, DynamicWorkspace2 ]`?

Yeah. It was late night, and my brain decided that workspace index == workspace id, and then things got confusing.

**Comment by algernon** [comment]
> Pretty sure the only place where removing happens is `Monitor::clean_up_workspaces()`, so no need for structural changes.

`remove_window()` appears to remove workspaces too, so two places total. I think a newtype here would be nice. Still not a lot. I'll go with copying the logic for now, see how that feels.

**Comment by YaLTeR** [comment]
Named workspaces are now merged! Thanks @algernon for implementing it. Documentation: https://github.com/YaLTeR/niri/wiki/Configuration:-Named-Workspaces
