### ISSUE TITLE
Hover popups from waybar are rendered under workspace windows

### ISSUE THREAD

**Issue by cole-h** [YaLTeR/niri#298]
Hello! I recently started experimenting with niri, and so far it's awesome!

However, something I noticed is that, when using a mostly default niri config and a completely default waybar config, hover popups from waybar segments can be drawn under workspace windows, as you can see in the following screenshot:

![image](https://github.com/YaLTeR/niri/assets/28582702/0c4c197a-f347-4b62-ae87-7b34aa0dadbc)

(I'm pretty sure this specific issue hasn't been reported before, but my search-fu may be weak. Possibly related to https://github.com/YaLTeR/niri/issues/125.)

### System Information

* niri version: 6a80078259ca3e3854b0748a15e98c7293d0822a

(Sorry for not following the exact format in the template, I'm using niri from Nix which doesn't have the commit information embedded in the build.)

* GPU: NVIDIA RTX 4090

* CPU: Intel Core i9-13900k

**Comment by YaLTeR** [comment]
Hello, set `"layer": "top"` in the Waybar config. By default it is on the bottom layer which is behind windows, and niri currently renders popups on the same level as the parent surface itself.

**Comment by cole-h** [comment]
Thanks for the quick response!

Would you be amenable to me adding this information to the wiki? (Maybe by adding waybar to the "Important Software" page, and noting this behavior?)

**Comment by YaLTeR** [comment]
It's already mentioned [here](https://github.com/YaLTeR/niri/wiki/FAQ#why-is-the-waybar-pop-up-menu-showing-behind-windows) and [here](https://github.com/YaLTeR/niri/wiki/Layer%E2%80%90Shell-Components). :smile: Honestly we should just start rendering the popups on top since that's what other compositors seem to do.

**Comment by cole-h** [comment]
Oh my goodness, I can't believe I didn't notice the FAQ page............... sorry about that........ :sweat_smile:

**Comment by jc00ke** [comment]
I believe it is set correctly:

https://github.com/jc00ke/dotfiles/blob/47d37953555e8b475a5dd20c44f55e3e0b1036d6/.config/waybar/config.jsonc#L2

I've restarted Waybar, restarted my computer, et al. I see this on both my desktop (Debian) that I'm on now and my laptop (Arch, for now.)

**Comment by jeLee6gi** [comment]
> I believe it is set correctly:
> 
> https://github.com/jc00ke/dotfiles/blob/47d37953555e8b475a5dd20c44f55e3e0b1036d6/.config/waybar/config.jsonc#L2
> 
> I've restarted Waybar, restarted my computer, et al. I see this on both my desktop (Debian) that I'm on now and my laptop (Arch, for now.)

`"mode": "dock"` is a preset which sets values for `"layer"`, `"exclusive"`, `"passthrough"` and `"visible"`

https://github.com/Alexays/Waybar/blob/481b01d9af1e34b7501665bbfc0b19fce5082eb5/src/bar.cpp#L25-L55

Your waybar should be running on the bottom layer because of that, you can verify using `niri msg layers`

**Comment by YaLTeR** [comment]
This is no longer an issue on niri 25.01 btw
