### ISSUE TITLE
Screen is off on version 0.1.5 (NixOS)

### ISSUE THREAD

**Issue by diego-est** [YaLTeR/niri#323]
When launching niri from the tty I get a black screen. More specifically, the physical screen is off. Notwithstanding I can send keystrokes to the niri compositor and they get interpreted and executed. I tried this by pressing `Mod+Shift+E` and being able to exit the compositor.

Running niri with `RUST_BACKTRACE=full` didn't give any more output than running niri without it. Which, I assume, means that this failure occurs silently.

I noticed that version 0.1.4 does not have any of the above mentioned issues. I am currently typing this from `niri 0.1.4` on the same computer and same configuration.

### System Information

* niri version: `niri 0.1.5 (unkown commit)`

* Distro: NixOS (nixpkgs-unstable branch)

* GPU: Intel Raptor Lake-P [Iris Xe Graphics]

* CPU: 13th Gen Intel i7-1360P (16) @ 5.000GHz

PS: If you need any more debugging output I will gladly run tests and collect data. I would also like to work on this issue if possible.

**Comment by Wiener234** [comment]
I have not tested it with niri 0.1.4 but i have the same problem that it niri is launching from tty or login-manager but only displays a black screen.

That is the error log that i get:

`[2m2024-05-02T11:21:46.366761Z[0m [32m INFO[0m [2mniri[0m[2m:[0m starting version 0.1.5 (unknown commit)
[2m2024-05-02T11:21:46.384810Z[0m [34mDEBUG[0m [2mniri_config[0m[2m:[0m loaded config from "/home/nils/.config/niri/config.kdl"
libinput error: event14 - Tablet Monitor Touch Strip: libinput bug: missing tablet capabilities: pen btn-stylus resolution. Ignoring this device.
libinput error: event15 - Tablet Monitor Dial: libinput bug: missing tablet capabilities: pen btn-stylus resolution. Ignoring this device.
[2m2024-05-02T11:21:46.676839Z[0m [32m INFO[0m [2mniri::backend::tty[0m[2m:[0m using as the render node: "/dev/dri/renderD128"
[2m2024-05-02T11:21:46.696117Z[0m [34mDEBUG[0m [2mniri::backend::tty[0m[2m:[0m device added: 57857 "/dev/dri/card1"
[2m2024-05-02T11:21:46.696529Z[0m [33m WARN[0m [2mniri::backend::tty[0m[2m:[0m error adding device: DRM access error: Error loading resource handles on device `Some("/dev/dri/card1")` (Operation not supported (os error 95))

Caused by:
    Operation not supported (os error 95)
[2m2024-05-02T11:21:46.696543Z[0m [34mDEBUG[0m [2mniri::backend::tty[0m[2m:[0m device added: 57856 "/dev/dri/card0"
MESA-LOADER: failed to open simpledrm: /usr/lib/dri/simpledrm_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/dri, suffix _dri)
[2m2024-05-02T11:21:46.716997Z[0m [33m WARN[0m [2mniri::backend::tty[0m[2m:[0m error adding device: None of the following EGL extensions is supported by the underlying EGL implementation, at least one is required: ["EGL_EXT_device_drm"]
[2m2024-05-02T11:21:46.717017Z[0m [32m INFO[0m [2mniri[0m[2m:[0m listening on Wayland socket: wayland-1
[2m2024-05-02T11:21:46.717020Z[0m [32m INFO[0m [2mniri[0m[2m:[0m IPC listening on: /run/user/1000/niri.wayland-1.1522.sock
[2m2024-05-02T11:21:48.247843Z[0m [32m INFO[0m [2mniri::input[0m[2m:[0m quitting after confirming exit dialog
`

**Comment by YaLTeR** [comment]
What device / CPU / GPU is that? Some of them just don't work yet. But it's extra strange if it worked in 0.1.4 then broke.

**Comment by Wiener234** [comment]
GPU: Nvidia 1050
CPU: Intel i7-8700k
Distro: arch installed from offical repos

**Comment by YaLTeR** [comment]
Yeah that sounds like not quite supported Nvidia configuration

**Comment by Wiener234** [comment]
is there some way to find out what is supported?

**Comment by YaLTeR** [comment]
Not sure exactly, but it needs to be a relatively recent Nvidia GPU + driver with GBM and kernel modeset. Would also be interesting to try if cosmic-comp works, because if it does, then it's something I may be able to fix in niri.

**Comment by YaLTeR** [comment]
> error adding device: Illegal seek (os error 29)

huh, wat? Haven't seen that one before. Thanks for posting this

**Comment by diego-est** [comment]
After doing some testing it seems that it only throws this error if I launch version `0.1.5` from the TTY. (launching it from inside a running wayland session works fine).

Additionally, I tested the commits for the "releases" of versions `0.1.5`, `0.1.4` and `0.1.3` and they all throw the same error. Which means that the only working version as of now is whatever is getting pulled from nixpkgs for version `0.1.4`

**Comment by YaLTeR** [comment]
Hmm, okay, that makes me suspect that it's not niri. I believe a common problem with nix is that mesa drivers are out of sync with niri, could you check that please?

**Comment by Wiener234** [comment]
> Not sure exactly, but it needs to be a relatively recent Nvidia GPU + driver with GBM and kernel modeset. Would also be interesting to try if cosmic-comp works, because if it does, then it's something I may be able to fix in niri.

found the problem. i had no kernel modeset. Thanks for the help :)

**Comment by Wiener234** [comment]
I followed that guide https://github.com/korvahannu/arch-nvidia-drivers-installation-guide
my graphics card was not properly set up

**Comment by diego-est** [comment]
Thank you @Wiener234 for mentioning the kernel parameters thing. `niri 0.1.5 (unkown commit)` now runs on my system!

Adding the kernel parameter mentioned in the Nix guide for [Intel Graphics](https://nixos.wiki/wiki/Intel_Graphics) fixed this. Thank you all for the help!

**Comment by YaLTeR** [comment]
Awesome, mentioned these on the getting started wiki page.
