### ISSUE TITLE
Implement key repeat for compositor bindings

### ISSUE THREAD

**Issue by YaLTeR** [YaLTeR/niri#345]
### Discussed in https://github.com/YaLTeR/niri/discussions/344

**Comment by YaLTeR** [comment]
Apparently sway does key repeat for all bindings; GNOME does key repeat at least for custom spawn bindings. So it's probably worth to do key repeat for everything by default and have a flag to disable it?

**Comment by SalmanFarooqShiekh** [comment]
I think no key-repeat makes sense more of the times than key-repeat does. What are the bindings which one would preferably want to have repeat enabled on? This is without thinking much but I can only think of volume and brightness relative adjustments. Most other binds are for stuff like launch an app, run a command, etc. which I think don't need repeats.

Really, I don't have any preference for the default of binding key-repeat enabled/disabled. Either way will be good.

And, thank you so much for the awesome compositor. I have been dailying it since this weekend for backend and frontend web-development and it is working really nicely especially with multi-monitors. Touchpad gestures and the animations are really nice and it is obvious considerable work went into properly tuning them.

**Comment by SalmanFarooqShiekh** [comment]
I guess some people would like to have Mod+H/J/K/L etc. (in the default config) to repeat too when held.

**Comment by YaLTeR** [comment]
I think it's pretty standard to have repeat for changing focus and stuff (which is a lot of the commands), then for spawning GNOME seems to also do it, so why not.

**Comment by YaLTeR** [comment]
This is now implemented.
