### ISSUE TITLE
fractional scaling support

### ISSUE THREAD

**Issue by kchibisov** [YaLTeR/niri#35]
The protocol is supported by smithay, however it means that downscaling/upscaling could be required for some stuff. And the layout-ing could be more complicated than what it is right now due to pixel rounding and the fact that scale might not exactly match the monitor resolution.

**Comment by vollowx** [comment]
Also really need this!

**Comment by YaLTeR** [comment]
Note: this will require refactoring some rendering-related parts of niri, and this will also require changes / fixes to Smithay, to allow its render elements operate in physical pixels where appropriate. Currently it's difficult / impossible to draw compositor-side UI elements (like borders or the important hotkeys dialog) pixel-perfectly.

**Comment by vollowx** [comment]
Thanks for the quick reply. No hurry just wish you all the best :heart:

**Comment by matejc** [comment]
@YaLTeR I like Niri, thanks for creating it. I would require fractional scaling to start fully using it. Is it possible to create a bunch of byte-sized tickets so that people can help? Even so that I am not very versed in Rust, I like a challenge... Also sponsoring for this feature is not out of the question.

**Comment by YaLTeR** [comment]
I'm not sure this is really bite-sized ticket material. Roughly what needs to be done is:

1. Adjust Smithay API design and implementation for some render elements to be able to operate in Physical space without going back and forth to Logical (to enable pixel-perfect rendering of compositor UI). Here's *one* of the problems to solve for example: https://github.com/Smithay/smithay/issues/1292 I'm not sure what changes are appropriate there, haven't looked into it. Maybe @cmeissl has a better idea.
2. Go through the code in niri very carefully and make it work with fractional scale. I suspect this one's on me.
3. Also fix some wp-viewporter bugs that are likely on the Smithay side; I'm not sure if there are issues for them as I had just bumped into them over the past 2 days.

**Comment by vollowx** [comment]
About the compositer-side UI elements, why not depend on a UI framework that supports fractional scaling like gtk?

**Comment by YaLTeR** [comment]
I mean, the problem at hand is that Smithay is missing a way to draw a rectangle at physical coordinates. The solution isn't difficult, just needs some API discussion. UI framework or not isn't really relevant here.

**Comment by cmeissl** [comment]
> I mean, the problem at hand is that Smithay is missing a way to draw a rectangle at physical coordinates. The solution isn't difficult, just needs some API discussion. UI framework or not isn't really relevant here.

wdym? The render element reports everything in physical space and is expected to draw in physical coordinates?
So I don't see a reason why it should not be possible to draw a rectangle at physical coordinates.

I guess you mean something different, the coordinate space in which most current implemented elements operate.
The wayland element follows the rules (or at least it should) defined in the core spec + fractional scale protocol.
A surface is only allowed to attach buffers with a sizes multiples of the logical size (1x, 2x, 3x,...), this also applies to
surfaces using the fractional scale protocol. So how does it work then? The client attaches a buffer with a size of 1 and uses viewporter to set the logical size. Together with the rounding rule defined in the protocol we end up with what we have today for fractional scale.

Why does this matter here? Because currently all elements follow exactly these rules (including the expectation about the buffer size) so that we should end with the same position and size for everything.

It may not matter for independent UI elements in the compositor, but for SSD we need to make sure everything follows the same rules.

I hope this gives some insights why we currently have this behavior and why we choose it.

**Comment by YaLTeR** [comment]
Yeah, I understand why it works the way it does, just tried to communicate the gist of what the problem is here.

**Comment by matejc** [comment]
Sorry to be late to the party. But form this I see that @YaLTeR and @cmeissl are not on the same page about this (forgive me if I do not understand correctly) and I think that you two need to be on the same page for this issue to go further into the implementation stage. So I am unsure if anyone else can help at the moment.

**Comment by YaLTeR** [comment]
No worries, I have a pretty clear understanding of what I need to do. I can write the render elements that I need in niri itself.

**Comment by YaLTeR** [comment]
Then once I see that my ideas work, we can think if and how we want to include them in Smithay.

**Comment by songww** [comment]
I'm looking forward to this feature as well

**Comment by YaLTeR** [comment]
Fractional scaling is now implemented in the main branch!
