### ISSUE TITLE
nix flake support

### ISSUE THREAD

**Issue by SomeGuyNamedMy** [YaLTeR/niri#5]
having a flake for the project would make developing on nixos much easier but i know many projects dont like the added maintenance.

**Comment by hallettj** [comment]
Oh hey, I had a similar thought. I made a flake just to try out the project for myself. I have it in a branch here: https://github.com/hallettj/niri/blob/nix-flake/flake.nix

It's not complete - on NixOS after the binary is built it has to be run with `steam-run` for Niri to find `libEGL.so.1`. I'm sure there's a way to fix that.

I also made a simpler package expression for my home manager config: https://github.com/hallettj/home.nix/blob/main/pkgs/niri.nix. It gets the job done without any changes needed to the Niri repo.

I'd be happy to provide Nix support if @YaLTeR wants it. But I don't want to be pushy about it. Some of the advantages of Nix for non-NixOS users are reproducible development environments, and CI setup that shares configuration with the development environment.

I'm very excited about Niri!

**Comment by YaLTeR** [comment]
Hey! I guess this is something that could be interesting, maybe some time down the line. I don't use nix myself (yet perhaps? :)) so somebody else will have to make the config, and it should be easy enough to keep updated. I'm not sure how projects typically set this up, do they do a CI build for the nix to ensure it keeps working fine?

**Comment by hallettj** [comment]
Typically a project has a `flake.nix` with code to handle any or all of: building the project, running tests and other checks, setting up dev shells. It does stuff like fetching a specific version of Rust and Cargo from nixpkgs, and fetching system dependencies like wayland, xkbcommon, etc. There is also a `flake.lock` which locks a specific version of nixpkgs, and locks Nix libraries used in the flake. I have an example here, https://github.com/YaLTeR/niri/commit/5bd7953648133fc5d417d3a55dc1ca48d129dc48 (In that example I configured the flake to use the same system dependencies as wlroots as a quick shortcut.)

Optionally you have a `.envrc` that automatically loads a dev environment when changing into the project directory for people who have direnv setup, and who opt in to running the `.envrc` script for the project. That adjusts your `PATH` and other env variables so that your shell uses the Rust, Cargo, and system dependencies that come through the Nix config. If you choose not to include a `.envrc` then Nix users can get almost the same effect by starting a shell with `nix develop`.

Once you have those set up anyone with Nix set up can work on the project more easily because all dependencies and build scripts are set up automatically. That's not limited to NixOS - the Nix package manager can be installed on other OSes. I used Nix on Debian while working on Rust projects until recently switching to NixOS.

Furthermore anyone with Nix would be able to install Niri directly from the Github repo. It's not strictly necessary ship a package with nixpkgs. (But there are some reasons that can be a good idea, such as getting prebuilt binaries into Nix's official binary cache.) If the project flake is extended with a NixOS module that can provide automatic login manager configuration, systemd units, etc. - but only on NixOS.

Yes, a CI build is a good idea. There is a Github action that [installs Nix](https://github.com/marketplace/actions/install-nix) on Github's default Ubuntu images. It takes about 4 seconds to run. Then you run `nix build` to verify the package builds, and optionally `nix flake check` if you want to run tests using the Nix config. Again, the flake sets up project dependencies so you only need those two steps in the CI config.

There is another Github action that [provides Nix-specific caching](https://determinate.systems/posts/magic-nix-cache) which is helpful because it creates separate cache buckets for each compiled Rust dependency. (I'm just noticing the provider of that action also provides their own Nix installer, and now I'm thinking of switching to use that for my current project.)

Maintenance would mostly come up when non-Cargo dependencies change. For example switching to a newer Rust version, adding a system dependency, switching to a version of wayland newer than the one locked in `flake.lock`. The flake I wrote also has a list of "extra source files" which would need to be updated when necessary.

**Comment by YaLTeR** [comment]
Thanks a lot for the detailed explanation! I see how it works now.

The example looks fairly understandable and the maintenance sounds pretty reasonable; is there some workflow for figuring out how a particular native dependency is called in nix? I.e. `dnf provides /usr/lib64/libsomething.so` in Fedora.

Also, do I understand correctly that your flake only builds the niri binary, and doesn't install `resources/niri-session` etc?

As for cached prebuilt binaries, niri is a bit too early in development for those I'm afraid. :)

**Comment by hallettj** [comment]
> The example looks fairly understandable and the maintenance sounds pretty reasonable; is there some workflow for figuring out how a particular native dependency is called in nix? I.e. `dnf provides /usr/lib64/libsomething.so` in Fedora.

The [nix-index-database](https://github.com/nix-community/nix-index-database) flake provides a `nix-locate` command along with an index of all files in all packages in nixpkgs. There are instructions for installing it to get `nix-locate`. It can also be run without installing like this:

```
$ nix run github:nix-community/nix-index-database libEGL.so.1
```

> Also, do I understand correctly that your flake only builds the niri binary, and doesn't install `resources/niri-session` etc?

That's correct. The flake needs more work. And as I mentioned in my previous comment it also should be fixed so that Niri can find `libEGL.so.1` without resorting to running Niri with `steam-run`. (A quirk of Nix is that lots of problems can be fixed using `steam-run`. But in this case I'm sure there is a better way.)

> As for cached prebuilt binaries, niri is a bit too early in development for those I'm afraid. :)

Yep, makes sense. I expect to do lots of builds which is why I used `crane` in the flake to manage the build. It Does some extra steps to build Cargo dependencies separately so that later builds can reuse cached builds from /nix/store for dependencies that haven't changed.

**Comment by kchibisov** [comment]
It's not clear why a particular package manager should be supported by the upstream projects in the first place. Let's say you add flake support, then you have guile, gentoo ebuilds, and so on, and one can come up with some other package format the other day. In general, what you want sounds like an `INSTALL.md` telling which packages should be installed on what system to get the project compile and running.

I'd guess that you want flake support, because the use of `dlopen` and it could be hard to figure what exactly needed during runtime because of that. In general, just adding `LD_LIBRARY_PATH` should do the job to get the development done. And you have `strace` to let you figure, because upstream shouldn't really tell you that you need `libEGL` in runtime, when it says that it wants mesa or uses OpenGL.

**Comment by SomeGuyNamedMy** [comment]
Just going to go ahead and close this issue for now, I'll just maintain my one fork with a flake to contribute.
