### ISSUE TITLE
Tauri / gg menu popups are not recognized as popups, open into a new column

### ISSUE THREAD

**Issue by tv42** [YaLTeR/niri#521]
I was testing the version control GUI at https://github.com/gulbanana/gg
It's written with https://tauri.app/ which I think in this case is just binding to gtk3 and webkitgtk-4.1

It seems right mouse button popup menus from clicking the commits in the left pane open into a new niri column.

I don't know if this is something Tauri does weirdly, or what.

### System Information

* niri version: niri 0.1.6 (unknown commit)

* Distro: NixOS-24.05

* GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics] (rev 01)

* CPU: Intel 11th gen i7-1165G7

**Comment by YaLTeR** [comment]
You could dive into WAYLAND_DEBUG to be sure, but this is very likely a tauri issue, since toplevel windows use entirely different Wayland objects from popups or subsurfaces. Which also makes me wonder how it's supposed to work at all, as on Wayland clients cannot position toplevel windows in any way (in contrary to popups and subsurfaces).

If tauri uses winit, then that's why, it doesn't support them yet.

**Comment by YaLTeR** [comment]
Closing because this is very likely a client bug.
