### ISSUE TITLE
Weird large borders on Slack window

### ISSUE THREAD

**Issue by minego** [YaLTeR/niri#604]
After a recent update, suddenly every time I open Slack, it sizes itself oddly and has very wide borders. My config has normal borders turned off, and the focus-ring border width is set to 1.

The size of the window is clearly smaller in all dimensions than it should be, but I don't see why.

```
layout {
    gaps 10
    struts {
        left -10
        right -10
        top -10
        bottom -10
    }
    focus-ring {
        width 1
        active-color "faff00"
        inactive-color "0f0f0f"
    }
    border { off; }
}
```

### System Information

* niri version: niri stable 0.1.8

* Distro: NixOS unstable

* GPU: AMD Radeon APU 780M

* CPU: Ryzen 7 8840U

# Slack when it is active:
![image](https://github.com/user-attachments/assets/5dc3e18e-9b7c-4056-a117-6912105e8941)

# Slack when it is not the active window:
![image](https://github.com/user-attachments/assets/47308fa9-fbf0-4e9c-b78d-9d2b381b4522)

# An example of the size any other window takes in the same layout
![image](https://github.com/user-attachments/assets/83944980-e72e-428f-8c30-217ad1dfd828)

**Comment by YaLTeR** [comment]
This is probably some chromium issue, I've seen it assume weird sizes until a resize.

**Comment by minego** [comment]
> This is probably some chromium issue, I've seen it assume weird sizes until a resize.

I think there may be something to that... Slack, and electron apps, etc can be ...weird.

That being said, it doesn't change if I resize the window. Regardless of the window size the borders are always like that.

Also, I haven't been able to reproduce it in any other applications so far. Chromium doesn't do it. I haven't tried a lot of other electron apps though.

**Comment by YaLTeR** [comment]
Looks an awful lot like it sizes the entire buffer (with CSD shadows) to the requested size, instead of just windows contents.

**Comment by minego** [comment]
Oh, interesting. That does seem plausible. I don't know why that one application would be trying to do that though...

**Comment by minego** [comment]
Well, I enabled the `prefer-no-csd` option, and that fixes it. So, it does indeed seem to be caused by client side decorations.

I'm happy with this solution. If you think this is still a bug that should be addressed, feel free to reopen.

**Comment by bbb651** [comment]
This also happens on Vesktop (`1.5.3`, Electron `31.1.0`. I couldn't reproduce this on chromium without electron, e.g. brave PWAs work as expected).

This seems relevent from [xdg_toplevel.configure](https://wayland.app/protocols/xdg-shell#xdg_toplevel:event:configure):
> The width and height arguments specify a hint to the window about how its surface should be resized in window geometry coordinates. See set_window_geometry.

I seems like niri is correctly giving the size in window geometry coordinates, but electron is incorrectly setting the surface size as is without accounting for them.

~~I think the oversized focus rings are niri's fault, it seems like it doesn't look at the [window geometry](https://wayland.app/protocols/xdg-shell#xdg_surface:request:set_window_geometry)~~ nevermind, it's probably handled somewhere in smithay, after some digging turns out electron is straight up setting it's shadow as part of the window geometry:
```
[1737274.145]  -> xdg_surface@46.set_window_geometry(0, 0, 936, 1028)
```
I have borders set to `3`, which works out to `1028 + 2*3 = 1034` which exactly matches the focus ring size.

I think an additional window rule option to set struts to be used with `clip-to-geometry` will be a good workaround and sounds useful in general.

**Comment by YaLTeR** [comment]
> electron is straight up setting it's shadow as part of the window geometry

Yeah, that's definitely wrong.

> I think an additional window rule option to set struts to be used with clip-to-geometry will be a good workaround and sounds useful in general.

I can't really think of any other cases where it could be useful. Chromium or Electron should just be fixed.
