### ISSUE TITLE
Keyboard input which wakes system should be discarded

### ISSUE THREAD

**Issue by vilhalmer** [YaLTeR/niri#853]
When waking the system with a keyboard press, the input is passed through after wake. This can lead to accidentally performing actions in the focused app when all you wanted to do was wake from sleep. Today I started a video playing in the active Firefox tab and scared myself :D

Ideally any key presses which occur before the display has been turned back on should be ignored. I'm not certain whether niri can determine when this happens, just discarding for a fixed period (<= 1 second) after wake is probably sufficient as well.

### System Information

* niri version: niri 0.1.10 (v0.1.10-13-g1a0612c)

* Distro: Arch

* GPU: Intel Corporation Raptor Lake-P [Iris Xe Graphics] (rev 04)

* CPU: 13th Gen Intel(R) Core(TM) i5-1340P

**Comment by YaLTeR** [comment]
Do you mean wake from sleep, or wake as in power on monitors?

**Comment by vilhalmer** [comment]
Wake from sleep, in this case a laptop with the lid closed and attached to a hub. Not sure if this occurs with the internal keyboard.

**Comment by YaLTeR** [comment]
I suspect it depends on the hardware whether the waking key press makes it to the compositor because on my laptop it does (so I wake with the first character of my password), but on my other systems it does not. I'm also not sure if niri can even detect this, since sleep is outside its domain.

**Comment by vilhalmer** [comment]
I don't remember this happening in sway, but I'll have to reinstall it to confirm or deny. That also could be a bug in wlroots that I was just treating as a feature, too.

**Comment by salman-farooq-sh** [comment]
Is there any way to discard input while powering on monitors after `niri msg action power-off-monitors`? Is this even a thing other projects do? Monitor waking up time can range from very quick (built-in laptop screen) to very slow (some external ones).

**Comment by vilhalmer** [comment]
My thought was maybe it could watch for a DRM connector event, but I don't know how plausible that is. I'm sure whether it disappears or not also varies between hardware. This is probably not worth adding a feature for if it's unknowable. I also don't think it needs to actually discard all input until the screen is visible, if just the first press could be handled differently that would be good enough. (i.e. "detected monitor reconnecting, if anything in buffer discard"?)

**Comment by salman-farooq-sh** [comment]
For this, we just handle `niri msg action power-on-monitors` (and also the automatic one that happens) only after `niri msg action power-off-monitors` is explicitly called. So that solves the "when" of it.

Regarding how much input to ignore, there are a few options:
1. Ignore for a fixed time
1. Ignore the first input
1. Ignore until the first different key, like pressing the space bar a few times would do nothing until a different key is pressed
1. ...more?

How would 2 and 3 work for touchscreens/trackpads?

**Comment by salman-farooq-sh** [comment]
Note that I am not talking about system suspend/sleep, just monitor power-on/off.

**Comment by salman-farooq-sh** [comment]
This can be done with `evtest --grab` too I think but I just wanted to know other people's opinions on it being built into the compositor.

**Comment by YaLTeR** [comment]
> My thought was maybe it could watch for a DRM connector event, but I don't know how plausible that is. I'm sure whether it disappears or not also varies between hardware.

Pretty sure it does not disappear across sleep.

> Is there any way to discard input while powering on monitors after `niri msg action power-off-monitors`? Is this even a thing other projects do? Monitor waking up time can range from very quick (built-in laptop screen) to very slow (some external ones).

I don't think others do this because I am quite used to just starting to type my password out of powered-off monitors, and all the inputs make it. (And I got quite annoyed when Windows 10 added an extra required key press that just brings up the password entry.)

> `niri msg action ignore-input 200`

Something like this could be done but again, is it really needed, even for power-on-monitors?

I don't think it can help with resume from sleep at least since I don't think you can detect it fast enough.

**Comment by salman-farooq-sh** [comment]
> I don't think it can help with resume from sleep at least since I don't think you can detect it fast enough.

Yup.

> Something like this could be done but again, is it really needed, even for power-on-monitors?

Not needed compositor-side necessarily as can be done through `evtest --grab` too, but the use-case is when you are not using a lockscreen and applications would do (potentially catastrophic) random actions when you or someone else presses a bunch of random buttons seeing that the screen was off. The lockscreen use-case is valid too that's why this can be something only available when explicitly required and used e.g. as in the suggested `ignore-input` command.

The only reason for baking it into the compositor is maybe you will have to grab each input device separately whereas the compositor can just ignore inputs a bit easier? I know you can whip up something to grab everything with evtest too including random keyboards and mice getting attached and detached.

On second thought, this is best left not being added to niri itself in my opinion. There are other more important things to do niri-side. Plus an external solution will keep things modular.

I think this issue can be closed now? @vilhalmer

**Comment by vilhalmer** [comment]
Yep, works for me. Thanks for the discussion!
