### ISSUE TITLE
`workspace_auto_back_and_forth` 

### ISSUE THREAD

**Issue by Kha** [YaLTeR/niri#88]
Hi, let me preface this feature request with stating that I very much enjoy niri and it basically feels production-ready for me.

One nicety I've become used to in i3 and sway is [`workspace_auto_back_and_forth`](https://i3wm.org/docs/userguide.html#workspace_auto_back_and_forth) which lets you quickly switch to a workspace and back by hitting the same key combination twice. I think it would be just as handy to have in niri.

**Comment by YaLTeR** [comment]
Hey, I assume this is only for Mod+digit binds and not for Mod+PgUp/Down in the default config? Would it make sense to have that option's behavior by default rather than as an option? I myself don't really use Mod+digit.

**Comment by Kha** [comment]
Ah, I hadn't even seen Mod+Pg before. But I usually have around 5 workspaces open and then Mod+digit becomes more comfortable. Having it as the default behavior would be fine with me, yes!

**Comment by YaLTeR** [comment]
> not allowing for gaps in the numbering

This is because niri uses dynamic workspaces like GNOME, where gaps don't really make sense, since empty workspaces in the middle disappear. It's not an inherent requirement to have dynamic workspaces, just that over my years of GNOME usage I've grown to like dynamic workspaces more than static ones. Mod+digit hotkeys just work on top of that.

> missing IPC for naming and displaying them in waybar

I looked at waybar and it seems that it uses special plugins for both sway and hyprland, i.e. there's no shared system for communicating workspaces between a bar and a compositor. Other than coming up with how an IPC could work in a way that makes the most sense, there isn't really anything else stopping this.

I was thinking of adding a built-in bar which would show workspaces which would allow animating the transitions in a better way compared to any external bar, but that also doesn't block adding an IPC for external bars.

**Comment by YaLTeR** [comment]
I tried implementing this, and it seems that with the current code it'll need a ton of checks and edge case handling all over the layout code, because workspaces are tracked by index, and the index needs to change potentially any time a workspace is removed, added or moved inside or between monitors. I guess I need to come up with a better way to keep track of this.

**Comment by Kha** [comment]
I see, it makes sense that this is more complicated and perhaps inadvisable with dynamic workspaces.

**Comment by YaLTeR** [comment]
Hey, thank you!

> Does a new bar make sense, I mean, right now?

If you mean my comment about a built-in bar, that's one of the "bigger and less clear and sometime in the future when I feel like it" ideas. It does make sense because that's the only way to get good animations for workspace switch and whatnot. I understand not everyone will want to use a built-in bar though so it'll be disable-able, whenever it happens.

> As far as I understand https://github.com/YaLTeR/niri/issues/135 should allow us to configure waybar (and probably others) to make workspaces less invisible.

That is correct.

> I'd be very interested in urgent hints for workspaces, once we can see them in a bar?

Urgency depends on #30 and then I guess if the ext-workspace-unstable protocol has that hint then it will work.

**Comment by YaLTeR** [comment]
This unfortunately faces the exact same problems code wise. The "last workspace" would be stored by index, then it needs to be correctly updated in a hundred places if workspaces around it appear, disappear, move.

**Comment by YaLTeR** [comment]
Implemented in #253 with a great idea by @FluxTape to assign unique persistent IDs to workspaces!

**Comment by banderlog** [comment]
It could be switched on like:

```
# from https://github.com/niri-wm/niri/wiki/Configuration:-Input#workspace-auto-back-and-forth
input {
    workspace-auto-back-and-forth
}
```

**Comment by Sempyos** [comment]
You don't need the `true`
